package com.qihoo360.replugin.sample.host;

import android.os.Bundle;
import androidx.annotation.Nullable;
import androidx.fragment.app.Fragment;
import androidx.fragment.app.FragmentActivity;

import com.qihoo360.replugin.RePlugin;

/**
 * 打开插件中的Fragment
 * <p>
 * 作者 coder
 * 创建时间 2017/7/6
 */

public class PluginFragmentActivity extends FragmentActivity {


    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        /**
         * Note:
         *
         * If a plugin is a built-in plugin, the name of the plugin is the prefix of the file.
         * For example, the name of the demo1.jar plugin is demo1 (automatically generated by the host-gradle plugin),
         * and operations such as RePlugin.fetchClassLoader("demo1") can be performed.
         *
         * If a plugin is an external plugin installed via RePlugin.install("/sdcard/demo1.apk"),
         * you must dynamically get the name of the plugin to use:
         * PluginInfo pluginInfo = RePlugin.install("/sdcard/demo1.apk");
         * RePlugin.preload(pluginInfo); //time consuming
         * String name = pluginInfo != null ? pluginInfo.getName() : null;
         * ClassLoader classLoader = RePlugin.fetchClassLoader(name);
        */

        boolean isBuiltIn = true;
        String pluginName = isBuiltIn ? "demo1" : "com.qihoo360.replugin.sample.demo1";

        // Register the class of the relevant Fragment
        // Register a global Hook for intercepting the system. The XX class is oriented to the XX class in Demo1.
        // It is mainly used to directly use the class in the plugin in the xml.
        RePlugin.registerHookingClass("com.qihoo360.replugin.sample.demo1.fragment.DemoFragment", RePlugin.createComponentName(pluginName, "com.qihoo360.replugin.sample.demo1.fragment.DemoFragment"), null);
        setContentView(R.layout.activity_plugin_fragment);

        // Code to use the plugin Fragment
        ClassLoader d1ClassLoader = RePlugin.fetchClassLoader(pluginName);//获取插件的ClassLoader
        try {
            Class clz = d1ClassLoader.loadClass("com.qihoo360.replugin.sample.demo1.fragment.DemoCodeFragment");
            Object obj = clz.newInstance();

//            if (obj instanceof Fragment) {
//                Fragment fragment = (Fragment) obj;
//            } else if (obj instanceof android.app.Fragment) {
//                android.app.Fragment fragment = (android.app.Fragment) obj;
//            } else {
//                Class C = clz;
//                while (C != null) {
//                    System.out.println(C.getName());
//                    Object obj2 = C.newInstance();
//                    if (C.isInstance(obj2)) {
//                        System.out.println(C.getName());
//                    }
//                    if (C == androidx.fragment.app.Fragment.class) {
//                        Fragment fragment = (androidx.fragment.app.Fragment) obj2;
//                    }
////                    if (C.getClass() == androidx.fragment.app.Fragment.class.getClass()) {
////                        Fragment fragment = (androidx.fragment.app.Fragment) obj2;
////                    }
//                    if (C.getCanonicalName().compareTo(androidx.fragment.app.Fragment.class.getCanonicalName()) == 0) {
//                        Fragment fragment = (androidx.fragment.app.Fragment) obj2;
//                    }
//                    if (obj2 instanceof androidx.fragment.app.Fragment) {
//                        Fragment fragment = (androidx.fragment.app.Fragment) obj2;
//                    }
//                    C = C.getSuperclass();
//                }
//                for (Class c : clz.getClasses()) {
//                    System.out.println(c.getName());
//                }
//            }

            Fragment frag = (androidx.fragment.app.Fragment) obj;
            //Fragment fragment = d1ClassLoader.loadClass("com.qihoo360.replugin.sample.demo1.fragment.DemoCodeFragment").asSubclass(Fragment.class).newInstance();//使用插件的Classloader获取指定Fragment实例
            getSupportFragmentManager().beginTransaction().add(R.id.container2, frag).commit();//添加Fragment到UI
        } catch (InstantiationException e) {
            e.printStackTrace();
        } catch (IllegalAccessException e) {
            e.printStackTrace();
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }

    }
}
